services:
  backend:
    image: airplanes-api
    build:
      context: .
    ports:
      - "3000:3000"
    env_file:
      - path: .env
        required: true
  database:
    image: postgres:alpine
    ports:
      - "5432:5432"
    env_file:
      - path: .env
        required: true
